### ISSUE TITLE
IllegalArgumentException: features does not exist. [BUG]

### ISSUE THREAD

**Issue by gnani4444** [NVIDIA/spark-xgboost-examples#13] opened 2020-07-17 10:01 UTC
Hi 
I am trying to run XGBoost4j Spark 3.0 GPU version on the azure databricks.
I was following the procedure from [this post](https://github.com/NVIDIA/spark-xgboost-examples/blob/spark-3/getting-started-guides/csp/databricks/databricks.md) .
While I was running [Mortage-gpu notebook](https://github.com/NVIDIA/spark-xgboost-examples/blob/spark-3/examples/notebooks/python/mortgage-gpu.ipynb). I got this error "features does not exist". The code is expecting a feature with name "features". 
![Capture](https://user-images.githubusercontent.com/19526142/87773931-759eeb00-c841-11ea-9ca2-4fd6ec29b521.PNG)

Can anyone help me with this ? I am running it on azure databricks with 7.0 ML GPU runtime, with NC6 GPU worker and driver node, as mention in the post.
and

I had a doubt regarding GpuDataReader, I found that GpuDataReader was removed in the mortage notebook from its previous version. Does this might be the reason for this error. 
Newer Version:
![Capture2](https://user-images.githubusercontent.com/19526142/87774398-1beaf080-c842-11ea-9ee8-26f9a3257d81.PNG)
Older Version:
![Capture3](https://user-images.githubusercontent.com/19526142/87774435-273e1c00-c842-11ea-9e11-19748fdb4cbc.PNG)

Thanks in Advance

**Comment by wbo4958** [comment] 2020-07-20 00:36
Hi @gnani4444, the error "features does not exist" was caused by having not found rapids-4-spark.jar, Could you double-check if you have added radpis-4-spark jar?

GpuDataReader was introduced for spark 2.x. And it's not used for spark 3.x anymore.

**Comment by gnani4444** [comment] 2020-07-20 07:30
Hi @wbo4958 
I double checked it. I have installed rapids-4-spark.jar files for databricks.

![rapids_extracted_code](https://user-images.githubusercontent.com/19526142/87910595-e0416800-ca87-11ea-911d-34f6e4b009a9.PNG)
![rapids_intiation_code](https://user-images.githubusercontent.com/19526142/87910555-d455a600-ca87-11ea-97fd-613e23fb340e.PNG)
![save](https://user-images.githubusercontent.com/19526142/87910638-f2bba180-ca87-11ea-8a83-95f70827ef5d.PNG)

**Comment by wbo4958** [comment] 2020-07-20 09:34
Yeah. BTW, Could you have set **spark.plugins** ? like below?

```
--conf spark.rapids.memory.gpu.pooling.enabled=false
--conf spark.plugins=com.nvidia.spark.SQLPlugin
```

**Comment by firestarman** [comment] 2020-07-21 02:50
Seems you are missing some configures to enable GPU.
For a quick verification, you could try to add the configures in the Mortage-gpu notebook when creating the SparkSeesion.
``` Scala
spark = SparkSession.builder
    .config("spark.plugins", "com.nvidia.spark.SQLPlugin")
    .config("spark.rapids.memory.gpu.pooling.enabled",  false)
    .getOrCreate()
```

**Comment by gnani4444** [comment] 2020-07-21 05:48
Thanks @wbo4958 @firestarman 
It worked, Now I am able to run the benchmark model.

Some stages are skipped, Is that expected ?

![image](https://user-images.githubusercontent.com/19526142/88017544-88683700-cb43-11ea-8849-75908820652c.png)

**Comment by wbo4958** [comment] 2020-07-21 05:54
Hi @gnani4444, Thx for trying the sample. Please feel free to submit the issues or FEA.
Close this issue.

**Closed as completed by wbo4958** 2020-07-21 05:54 UTC

**Comment by firestarman** [comment] 2020-07-21 06:14
-- Some stages are skipped, Is that expected ?
I think yes.

**Comment by gnani4444** [comment] 2020-07-21 08:13
@firestarman @wbo4958 
It saved or cached some calculations. Is that right ?
or skipped some unwanted steps not useful for this case 
or an error which needs a deep dive

Can you share any notebook or code for hyper-parameter tuning using hyperopt, If you already have it..  Thanks in Advance.

**Comment by gnani4444** [comment] 2020-07-21 12:37
@firestarman @wbo4958 

I couldn't find featureImportances method for the model object. Can you guide me how to get feature importances.

**Comment by wbo4958** [comment] 2020-07-22 05:53
> @firestarman @wbo4958
> 
> I couldn't find featureImportances method for the model object. Can you guide me how to get feature importances.

Hi @gnani4444 pls file another issue, pls don't mess other issue up.
